# Generated by Django 3.1.4 on 2021-02-27 22:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text="Inserisci il nome completo dell'artista (niente se è un gruppo o se coincide con il nome d'arte)", max_length=40)),
                ('nome_darte', models.CharField(help_text="Inserisci il nome d'arte dell'artista", max_length=40)),
                ('is_Gruppo', models.BooleanField(default=False, help_text='Inserisci vero se è un gruppo, falso altrimenti')),
                ('wiki_url', models.TextField(blank=True, help_text="Inserisci l'URL di wikipedia, se esiste", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=40)),
                ('testo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('foto', models.ImageField(upload_to='images')),
                ('autori', models.ManyToManyField(help_text="Seleziona l'autore o gli autori", related_name='autori', to='sanremo.Artista')),
                ('interpreti', models.ManyToManyField(help_text="Seleziona l'interprete o gli interpreti", related_name='interpreti', to='sanremo.Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.FloatField()),
                ('categoria', models.CharField(choices=[('i', 'Interpretazione'), ('b', 'Brano'), ('o', 'Outfit')], help_text='Scegli la categoria da votare', max_length=1)),
                ('brano', models.ForeignKey(help_text='Seleziona il brano', on_delete=django.db.models.deletion.PROTECT, to='sanremo.brano')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
