# Generated by Django 3.1.4 on 2021-01-04 22:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.TextField(max_length=30, null=True)),
                ('nome_darte', models.TextField(null=True)),
                ('isGruppo', models.BooleanField(default=False)),
                ('wiki_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField()),
                ('testo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanremo.artista')),
                ('id_brano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanremo.brano')),
            ],
        ),
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanremo.artista')),
                ('id_brano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanremo.brano')),
            ],
        ),
    ]
