# Generated by Django 3.1.4 on 2021-01-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='cognome',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome_darte',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brano',
            name='titolo',
            field=models.CharField(max_length=40),
        ),
    ]
