# Generated by Django 3.1.4 on 2021-02-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brano',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='brano',
            name='testo',
            field=models.TextField(blank=True, help_text='Inserisci il testo del brano', null=True),
        ),
    ]
