# Generated by Django 3.1.7 on 2021-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0002_auto_20210228_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='nome_completo',
            field=models.CharField(blank=True, help_text="Inserisci il nome completo dell'artista (niente se è un gruppo o se coincide con il nome d'arte)", max_length=40, null=True),
        ),
    ]
