# Generated by Django 3.1.4 on 2021-01-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0002_auto_20210104_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autore',
            old_name='id_artista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='autore',
            old_name='id_brano',
            new_name='brano',
        ),
        migrations.RenameField(
            model_name='interprete',
            old_name='id_artista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='interprete',
            old_name='id_brano',
            new_name='brano',
        ),
    ]
