# Generated by Django 3.1.4 on 2021-02-26 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanremo', '0003_auto_20210104_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.FloatField()),
                ('categoria', models.CharField(choices=[('i', 'Interpretazione'), ('b', 'Brano'), ('o', 'Outfit')], help_text='Scegli la categoria da votare', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='interprete',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='interprete',
            name='brano',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='isGruppo',
        ),
        migrations.AddField(
            model_name='artista',
            name='is_Gruppo',
            field=models.BooleanField(default=False, help_text='Inserisci vero se è un gruppo, falso altrimenti'),
        ),
        migrations.AddField(
            model_name='brano',
            name='autori',
            field=models.ManyToManyField(help_text="Seleziona l'autore o gli autori", related_name='autori', to='sanremo.Artista'),
        ),
        migrations.AddField(
            model_name='brano',
            name='interpreti',
            field=models.ManyToManyField(help_text="Seleziona l'interprete o gli interpreti", related_name='interpreti', to='sanremo.Artista'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cognome',
            field=models.CharField(help_text="Inserisci il cognome dell'artista (niente se è un gruppo)", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome',
            field=models.CharField(help_text="Inserisci il nome dell'artista o del gruppo", max_length=40),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome_darte',
            field=models.CharField(help_text="Inserisci il nome d'arte (niente se è un gruppo)", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='wiki_url',
            field=models.TextField(help_text="Inserisci l'URL di wikipedia, se esiste", null=True),
        ),
        migrations.DeleteModel(
            name='Autore',
        ),
        migrations.DeleteModel(
            name='Interprete',
        ),
        migrations.AddField(
            model_name='valutazione',
            name='brano',
            field=models.ForeignKey(help_text='Seleziona il brano', on_delete=django.db.models.deletion.PROTECT, to='sanremo.brano'),
        ),
        migrations.AddField(
            model_name='valutazione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
