# Generated by Django 3.1.4 on 2021-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0004_auto_20210227_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='wiki_url',
            field=models.TextField(blank=True, help_text="Inserisci l'URL di wikipedia, se esiste", null=True),
        ),
    ]
