# Generated by Django 3.1.4 on 2021-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanremo', '0005_auto_20210227_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='nome',
        ),
        migrations.AddField(
            model_name='artista',
            name='nome_completo',
            field=models.CharField(default='campo vuoto', help_text="Inserisci il nome completo dell'artista (niente se è un gruppo o se coincide con il nome d'arte)", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome_darte',
            field=models.CharField(default='campo vuoto', help_text="Inserisci il nome d'arte dell'artista", max_length=40),
            preserve_default=False,
        ),
    ]
